version: "3.9"
services:
  iped:
    image: iped-cuda:4.3.0
    privileged: true
    ulimits:
      nproc:
        soft: -1
        hard: -1
    command: >
      java -jar iped.jar -Xmx30G --portable
      __EVIDENCE_PATHS__
      -o "/results/__EVIDENCE_NAME_NOEXT__"
    volumes:
      - "./results:/results"
      - "./ipedtmp:/mnt/ipedtmp"
      __EVIDENCE_PATHS_VOLUMES__
      - "__HASHES_PATH__:/mnt/hashesdb:ro"
      - "__CONF_PATH__:/opt/iped/conf"
      - "./IPEDConfig.txt:/opt/iped/IPEDConfig.txt"
      - "./LocalConfig.txt:/opt/iped/LocalConfig.txt"
      - "./logs:/opt/iped/log"
      - "/etc/localtime:/etc/localtime:ro"
    devices:
      - "nvidia.com/gpu=all"
